[General]
__theme_updated__=1790565346417
__userfile__=true
icon_theme=WhiteSur
palette_override=false
single_click_activate=false
theme=kvantum-macos
tool_button_style=ToolButtonTextBesideIcon

[Qt]
doubleClickInterval=400
font="Inter,10,-1,5,50,0,0,0,0,0"
style=kvantum
wheelScrollLines=3
